"use client"

import * as React from "react"
import { useState } from "react"
import { T } from "@/lib/marketing/tokens"
import {
  FrostCard,
  Kicker,
  Pill,
} from "@/components/marketing/primitives"
import { SectionHeader } from "./SectionHeader"

export function ProSection() {
  return (
    <section
      id="pro"
      data-marketing-section="pro"
      style={{
        padding: "180px 40px 160px",
        borderTop: `1px solid ${T.frostDiv}`,
        position: "relative",
        overflow: "hidden",
        background: `linear-gradient(180deg, transparent 0%, ${T.voltFill} 38%, transparent 92%)`,
      }}
    >
      <div
        aria-hidden="true"
        style={{
          position: "absolute",
          top: "8%",
          right: "-15%",
          width: 860,
          height: 860,
          borderRadius: "50%",
          pointerEvents: "none",
          background: `radial-gradient(closest-side, ${T.voltFill}, transparent 68%)`,
          opacity: 0.7,
        }}
      />
      <div
        aria-hidden="true"
        style={{
          position: "absolute",
          bottom: "-10%",
          left: "-8%",
          width: 640,
          height: 640,
          borderRadius: "50%",
          pointerEvents: "none",
          background: `radial-gradient(closest-side, ${T.voltFill}, transparent 70%)`,
          opacity: 0.45,
        }}
      />

      <div
        style={{ maxWidth: 1280, margin: "0 auto", position: "relative" }}
      >
        <SectionHeader
          num="13"
          kicker="PRO · THE ANALYST DESK"
          title={
            <>
              Pro isn&apos;t a tier.
              <br />
              It&apos;s a{" "}
              <em
                style={{
                  fontFamily: T.fontDisplay,
                  fontStyle: "italic",
                  color: T.volt,
                }}
              >
                research desk.
              </em>
            </>
          }
          sub="The free tier gives you the collection. Pro gives you the receipts. On-demand dossiers, signature opinions, and market briefs — generated by grounded AI specialists, stored on each piece forever, viewable by every Pro member."
        />

        <div
          style={{
            marginTop: 80,
            padding: "18px 22px",
            borderTop: `1px solid ${T.frostDiv}`,
            borderBottom: `1px solid ${T.frostDiv}`,
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: 16,
          }}
        >
          <Kicker style={{ color: T.volt }}>
            THE DOCUMENTATION TRILOGY
          </Kicker>
          <div
            style={{
              display: "flex",
              gap: 24,
              fontFamily: T.fontMono,
              fontSize: 10.5,
              letterSpacing: 0.4,
              color: T.fg3,
            }}
          >
            <span
              style={{ display: "inline-flex", alignItems: "center", gap: 8 }}
            >
              <span
                style={{
                  width: 7,
                  height: 7,
                  borderRadius: 4,
                  background: T.fg1,
                }}
              />
              FACTUAL
            </span>
            <span
              style={{ display: "inline-flex", alignItems: "center", gap: 8 }}
            >
              <span
                style={{
                  width: 7,
                  height: 7,
                  borderRadius: 4,
                  background: "transparent",
                  border: `1px solid ${T.fg2}`,
                }}
              />
              COMMUNITY
            </span>
            <span
              style={{ display: "inline-flex", alignItems: "center", gap: 8 }}
            >
              <span
                style={{
                  width: 7,
                  height: 7,
                  borderRadius: 4,
                  background: "transparent",
                  border: `1px dashed ${T.fg3}`,
                }}
              />
              SENTIMENT
            </span>
          </div>
        </div>

        <div
          data-marketing-grid="pro-trio"
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(3, 1fr)",
            gap: 20,
            marginTop: 32,
          }}
        >
          <VARCard />
          <AARCard />
          <MarketPulseCard />
        </div>

        <div
          style={{
            marginTop: 100,
            padding: "40px 44px",
            borderLeft: `2px solid ${T.volt}`,
            maxWidth: 1000,
            marginLeft: "auto",
            marginRight: "auto",
          }}
        >
          <div
            style={{
              fontFamily: T.fontCaslon,
              fontStyle: "italic",
              fontSize: 28,
              lineHeight: 1.38,
              color: T.fg1,
              textWrap: "balance",
            }}
          >
            &quot;Every report cites its sources, tiers its confidence, and
            stays on the piece forever. No verdict language. No black-box
            outputs. An opinion you can act on — not a verdict we&apos;d never
            give you.&quot;
          </div>
          <Kicker style={{ marginTop: 22, color: T.fg3 }}>
            THE PRO COVENANT
          </Kicker>
        </div>

        <div
          style={{
            marginTop: 120,
            paddingTop: 80,
            borderTop: `1px solid ${T.frostDiv}`,
          }}
        >
          <div
            data-marketing-grid="pro-auto"
            style={{
              display: "grid",
              gridTemplateColumns: "1fr 1.15fr",
              gap: 80,
              alignItems: "center",
            }}
          >
            <div>
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <span
                  style={{
                    width: 22,
                    height: 22,
                    borderRadius: 11,
                    border: `1px solid ${T.voltBorder}`,
                    background: T.voltFill,
                    display: "inline-flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: T.volt,
                    fontFamily: T.fontDisplay,
                    fontSize: 14,
                  }}
                >
                  +
                </span>
                <Kicker color={T.volt}>AUTO-SHOWCASING</Kicker>
              </div>
              <h3
                style={{
                  fontFamily: T.fontDisplay,
                  fontWeight: 400,
                  fontSize: 56,
                  lineHeight: 0.98,
                  letterSpacing: -1.2,
                  margin: "22px 0 0",
                }}
              >
                Rules instead of{" "}
                <em
                  style={{
                    fontFamily: T.fontDisplay,
                    fontStyle: "italic",
                    color: T.volt,
                  }}
                >
                  curation.
                </em>
              </h3>
              <p
                style={{
                  fontSize: 16,
                  lineHeight: 1.6,
                  color: T.fg2,
                  marginTop: 24,
                  maxWidth: 460,
                }}
              >
                Showcases that populate themselves. Write the rule once —{" "}
                <em
                  style={{
                    fontFamily: T.fontCaslon,
                    fontStyle: "italic",
                    color: T.fg1,
                  }}
                >
                  any PSA 10 rookie I own over $5k
                </em>{" "}
                — and the Showcase reorganizes as your collection grows.
                Shopify Collections, built for the things you actually love.
              </p>
              <div
                style={{
                  marginTop: 28,
                  display: "flex",
                  gap: 24,
                  flexWrap: "wrap",
                }}
              >
                {(
                  [
                    ["REAL-TIME", "Updates as you upload"],
                    ["STACKED", "Chain rules with AND / OR"],
                    ["PRIVATE", "Share or keep for yourself"],
                  ] as const
                ).map(([k, v]) => (
                  <div key={k}>
                    <Kicker style={{ fontSize: 9.5, color: T.volt }}>
                      {k}
                    </Kicker>
                    <div
                      style={{
                        fontSize: 12.5,
                        color: T.fg2,
                        marginTop: 6,
                        maxWidth: 160,
                        lineHeight: 1.45,
                      }}
                    >
                      {v}
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <AutoShowcaseCard />
          </div>
        </div>

        <div
          style={{
            marginTop: 120,
            paddingTop: 36,
            borderTop: `1px solid ${T.frostDiv}`,
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: 16,
          }}
        >
          <div
            style={{
              fontFamily: T.fontCaslon,
              fontStyle: "italic",
              fontSize: 15,
              color: T.fg2,
              letterSpacing: 0.2,
            }}
          >
            Pro launches alongside the marketplace. Free users keep everything
            they have today.
          </div>
          <div
            style={{
              fontFamily: T.fontMono,
              fontSize: 11,
              color: T.fg3,
              letterSpacing: 0.5,
            }}
          >
            EARLY ADOPTERS GRANDFATHERED · DETAILS AT LAUNCH
          </div>
        </div>
      </div>
    </section>
  )
}

function VARCard() {
  const [hover, setHover] = useState(false)
  const rows: [string, string, "factual" | "community" | "sentiment"][] = [
    ["SUBJECT", "Luis Robert · Carolina League OBL", "factual"],
    ["AUTH", "PSA/DNA · Cert AZ58051", "factual"],
    ["CENSUS", "Matched · 14 certified examples", "factual"],
    ["PROVENANCE", "Goldin Auctions · May 2024", "community"],
    ["CONTEXT", "Rookie-year minor league ball", "sentiment"],
  ]
  return (
    <div
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        padding: 28,
        borderRadius: 18,
        position: "relative",
        background: "rgba(214,235,253,0.025)",
        border: `1px solid ${hover ? T.voltBorder : T.frostDiv}`,
        transition:
          "transform 280ms cubic-bezier(.2,.8,.2,1), border-color 200ms",
        transform: hover ? "translateY(-4px)" : "none",
        minHeight: 620,
        display: "flex",
        flexDirection: "column",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
        }}
      >
        <div>
          <Kicker style={{ color: T.volt }}>VAR · ANALYSIS REPORT</Kicker>
          <div
            style={{
              fontFamily: T.fontMono,
              fontSize: 10,
              color: T.fg3,
              marginTop: 6,
              letterSpacing: 0.5,
            }}
          >
            ID · VAR-2026-0247-K3
          </div>
        </div>
        <Pill variant="volt">GROUNDED</Pill>
      </div>

      <div
        style={{
          marginTop: 28,
          paddingBottom: 24,
          borderBottom: `1px solid ${T.frostDiv}`,
        }}
      >
        <Kicker style={{ fontSize: 9 }}>DOCUMENTARY RECORD FOR</Kicker>
        <div
          style={{
            fontFamily: T.fontDisplay,
            fontSize: 22,
            marginTop: 10,
            letterSpacing: -0.3,
            lineHeight: 1.18,
          }}
        >
          Luis Robert Signed OBL Baseball
        </div>
        <div
          style={{
            fontFamily: T.fontCaslon,
            fontStyle: "italic",
            fontSize: 13,
            color: T.fg2,
            marginTop: 6,
          }}
        >
          PSA/DNA · Cert AZ58051
        </div>
      </div>

      <div style={{ marginTop: 20, flex: 1 }}>
        {rows.map(([k, v, tier], i) => (
          <div
            key={k}
            style={{
              padding: "11px 0",
              borderTop: i ? `1px solid ${T.frostDiv}` : "none",
              display: "grid",
              gridTemplateColumns: "100px 1fr 14px",
              gap: 10,
              alignItems: "baseline",
            }}
          >
            <Kicker style={{ fontSize: 9 }}>{k}</Kicker>
            <div
              style={{
                fontFamily: T.fontMono,
                fontSize: 11.5,
                color: T.fg1,
                letterSpacing: 0.2,
                lineHeight: 1.45,
              }}
            >
              {v}
              <sup
                style={{
                  fontFamily: T.fontInter,
                  fontSize: 8,
                  color: T.volt,
                  marginLeft: 4,
                }}
              >
                [{i + 1}]
              </sup>
            </div>
            <span
              aria-label={tier}
              title={tier.toUpperCase()}
              style={{
                width: 7,
                height: 7,
                borderRadius: 4,
                marginLeft: "auto",
                background: tier === "factual" ? T.fg1 : "transparent",
                border:
                  tier === "factual"
                    ? "none"
                    : tier === "community"
                      ? `1px solid ${T.fg2}`
                      : `1px dashed ${T.fg3}`,
              }}
            />
          </div>
        ))}
      </div>

      <div
        style={{ display: "flex", gap: 6, marginTop: 20, flexWrap: "wrap" }}
      >
        <Pill variant="for_sale">COMPLETE DOCS</Pill>
        <Pill variant="sell_trade">2 EVIDENCE GAPS</Pill>
      </div>

      <div
        style={{
          marginTop: 18,
          paddingTop: 14,
          borderTop: `1px solid ${T.frostDiv}`,
          display: "flex",
          justifyContent: "space-between",
          fontFamily: T.fontMono,
          fontSize: 10,
          color: T.fg3,
          letterSpacing: 0.4,
        }}
      >
        <span>7 sources cited</span>
        <span>stored on piece forever</span>
      </div>
    </div>
  )
}

function AARCard() {
  const [hover, setHover] = useState(false)
  const dims: [string, "consistent" | "inconclusive"][] = [
    ["Letter formation", "consistent"],
    ["Flow", "consistent"],
    ["Proportion", "consistent"],
    ["Baseline angle", "consistent"],
    ["Embellishments", "consistent"],
    ["Ink / medium", "inconclusive"],
    ["Placement", "consistent"],
    ["Inscription", "consistent"],
  ]
  return (
    <div
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        padding: 28,
        borderRadius: 18,
        position: "relative",
        background: "rgba(214,235,253,0.025)",
        border: `1px solid ${hover ? T.voltBorder : T.frostDiv}`,
        transition:
          "transform 280ms cubic-bezier(.2,.8,.2,1), border-color 200ms",
        transform: hover ? "translateY(-4px)" : "none",
        minHeight: 620,
        display: "flex",
        flexDirection: "column",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
        }}
      >
        <div>
          <Kicker style={{ color: T.volt }}>AAR · AUTOGRAPH ASSESSMENT</Kicker>
          <div
            style={{
              fontFamily: T.fontMono,
              fontSize: 10,
              color: T.fg3,
              marginTop: 6,
              letterSpacing: 0.5,
            }}
          >
            ID · AAR-2026-0184-L1
          </div>
        </div>
        <Pill variant="volt">DUAL-GATE</Pill>
      </div>

      <div
        style={{
          marginTop: 24,
          padding: 20,
          borderRadius: 12,
          background: "rgba(0,0,0,0.42)",
          border: `1px solid ${T.frostDiv}`,
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            marginBottom: 10,
          }}
        >
          <Kicker style={{ fontSize: 8.5, color: T.fg3 }}>SUBJECT</Kicker>
          <Kicker style={{ fontSize: 8.5, color: T.fg3 }}>
            REFERENCE · 14 EXAMPLES
          </Kicker>
        </div>
        <svg
          viewBox="0 0 280 84"
          style={{ display: "block", width: "100%", height: 84 }}
        >
          <defs>
            <linearGradient id="aarBaseline" x1="0" y1="0" x2="1" y2="0">
              <stop offset="0" stopColor={T.volt} stopOpacity="0.0" />
              <stop offset="0.5" stopColor={T.volt} stopOpacity="0.35" />
              <stop offset="1" stopColor={T.volt} stopOpacity="0.0" />
            </linearGradient>
          </defs>
          <line
            x1="0"
            y1="62"
            x2="280"
            y2="62"
            stroke="url(#aarBaseline)"
            strokeWidth="1"
            strokeDasharray="3 4"
          />
          <path
            d="M 10 56 Q 22 18, 40 42 T 78 32 Q 94 20, 108 50 T 134 38"
            fill="none"
            stroke={T.fg1}
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
          <path
            d="M 152 56 Q 164 20, 182 44 T 220 34 Q 236 22, 250 52 T 276 40"
            fill="none"
            stroke={T.volt}
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeLinejoin="round"
            opacity="0.9"
          />
          <line
            x1="142"
            y1="8"
            x2="142"
            y2="76"
            stroke={T.frostDiv}
            strokeWidth="1"
          />
        </svg>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            marginTop: 8,
            fontFamily: T.fontMono,
            fontSize: 9.5,
            color: T.fg3,
          }}
        >
          <span>baseline · 3° Δ</span>
          <span>flow · continuous</span>
          <span>slant · +2° Δ</span>
        </div>
      </div>

      <div
        style={{
          marginTop: 18,
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: 0,
          flex: 1,
        }}
      >
        {dims.map(([label, state], i) => {
          const tone =
            state === "consistent"
              ? T.green
              : state === "inconclusive"
                ? T.orange
                : T.red
          return (
            <div
              key={label}
              style={{
                padding: "9px 10px",
                display: "flex",
                alignItems: "center",
                gap: 8,
                borderBottom: i < 6 ? `1px solid ${T.frostDiv}` : "none",
                borderRight: i % 2 === 0 ? `1px solid ${T.frostDiv}` : "none",
              }}
            >
              <span
                style={{
                  width: 6,
                  height: 6,
                  borderRadius: 3,
                  background: tone,
                  boxShadow:
                    state === "consistent" ? `0 0 5px ${tone}` : "none",
                  flexShrink: 0,
                }}
              />
              <span style={{ fontSize: 11, color: T.fg1 }}>{label}</span>
            </div>
          )
        })}
      </div>

      <div
        style={{
          marginTop: 18,
          padding: 14,
          borderRadius: 10,
          background: "rgba(17,255,153,0.06)",
          border: `1px solid rgba(17,255,153,0.25)`,
        }}
      >
        <Kicker style={{ fontSize: 9, color: T.green }}>
          DIRECTIONAL ASSESSMENT
        </Kicker>
        <div
          style={{
            fontFamily: T.fontDisplay,
            fontSize: 18,
            marginTop: 4,
            color: T.fg1,
            letterSpacing: -0.2,
          }}
        >
          Consistent with known examples
        </div>
        <div
          style={{
            fontSize: 11,
            color: T.fg2,
            marginTop: 6,
            fontFamily: T.fontCaslon,
            fontStyle: "italic",
            lineHeight: 1.45,
          }}
        >
          Formal authentication recommended · PSA/DNA, JSA, or Beckett
        </div>
      </div>
    </div>
  )
}

function MarketPulseCard() {
  const [hover, setHover] = useState(false)
  const buckets = [
    { label: "0-30d", h: 88, count: 14, fresh: true },
    { label: "31-60d", h: 64, count: 11, fresh: false },
    { label: "61-90d", h: 48, count: 8, fresh: false },
    { label: "91-180d", h: 76, count: 12, fresh: false },
    { label: "181-365d", h: 96, count: 17, fresh: false },
  ]
  return (
    <div
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
      style={{
        padding: 28,
        borderRadius: 18,
        position: "relative",
        background: "rgba(214,235,253,0.025)",
        border: `1px solid ${hover ? T.voltBorder : T.frostDiv}`,
        transition:
          "transform 280ms cubic-bezier(.2,.8,.2,1), border-color 200ms",
        transform: hover ? "translateY(-4px)" : "none",
        minHeight: 620,
        display: "flex",
        flexDirection: "column",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
        }}
      >
        <div>
          <Kicker style={{ color: T.volt }}>MARKET PULSE</Kicker>
          <div
            style={{
              fontFamily: T.fontMono,
              fontSize: 10,
              color: T.fg3,
              marginTop: 6,
              letterSpacing: 0.5,
            }}
          >
            ID · MP-2026-0521-N9
          </div>
        </div>
        <Pill variant="volt">
          <span
            style={{
              display: "inline-block",
              width: 5,
              height: 5,
              borderRadius: 3,
              background: T.volt,
              boxShadow: `0 0 5px ${T.volt}`,
              marginRight: 4,
              animation: "pulseGlow 1.4s ease-in-out infinite",
            }}
          />
          LIVE
        </Pill>
      </div>

      <div
        style={{
          marginTop: 28,
          paddingBottom: 20,
          borderBottom: `1px solid ${T.frostDiv}`,
        }}
      >
        <Kicker style={{ fontSize: 9 }}>BRIEF FOR</Kicker>
        <div
          style={{
            fontFamily: T.fontDisplay,
            fontSize: 20,
            marginTop: 8,
            letterSpacing: -0.3,
          }}
        >
          1986 Fleer Jordan #57 · PSA 10
        </div>
      </div>

      <div
        style={{
          marginTop: 18,
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: 10,
        }}
      >
        <div
          style={{
            padding: 12,
            borderRadius: 10,
            border: `1px solid rgba(17,255,153,0.25)`,
            background: "rgba(17,255,153,0.04)",
          }}
        >
          <Kicker style={{ fontSize: 9, color: T.green }}>FRESH · 0-30D</Kicker>
          <div
            style={{
              fontFamily: T.fontDisplay,
              fontSize: 22,
              marginTop: 6,
              color: T.fg1,
              letterSpacing: -0.3,
            }}
          >
            $86.2k
          </div>
          <div
            style={{
              fontFamily: T.fontMono,
              fontSize: 10,
              color: T.green,
              marginTop: 2,
            }}
          >
            +8.0% vs stale
          </div>
        </div>
        <div
          style={{
            padding: 12,
            borderRadius: 10,
            border: `1px solid ${T.frostDiv}`,
            background: "rgba(255,255,255,0.015)",
          }}
        >
          <Kicker style={{ fontSize: 9, color: T.fg3 }}>STALE · 181-365D</Kicker>
          <div
            style={{
              fontFamily: T.fontDisplay,
              fontSize: 22,
              marginTop: 6,
              color: T.fg1,
              letterSpacing: -0.3,
            }}
          >
            $79.8k
          </div>
          <div
            style={{
              fontFamily: T.fontMono,
              fontSize: 10,
              color: T.fg3,
              marginTop: 2,
            }}
          >
            baseline
          </div>
        </div>
      </div>

      <div style={{ marginTop: 20 }}>
        <div
          style={{ display: "flex", justifyContent: "space-between" }}
        >
          <Kicker style={{ fontSize: 9 }}>ABSORPTION · 365D</Kicker>
          <Kicker style={{ fontSize: 9, color: T.fg3 }}>62 SALES</Kicker>
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "flex-end",
            gap: 6,
            marginTop: 10,
            height: 104,
          }}
        >
          {buckets.map((b) => (
            <div
              key={b.label}
              style={{
                flex: 1,
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: 6,
              }}
            >
              <div
                style={{
                  fontFamily: T.fontMono,
                  fontSize: 8.5,
                  color: T.fg3,
                }}
              >
                {b.count}
              </div>
              <div
                style={{
                  width: "100%",
                  height: b.h,
                  borderRadius: 4,
                  background: b.fresh
                    ? T.volt
                    : `rgba(232,224,212,${b.h > 70 ? 0.35 : 0.20})`,
                  boxShadow: b.fresh
                    ? `0 0 10px rgba(232,224,212,0.40)`
                    : "none",
                  transition: "height 600ms cubic-bezier(.2,.8,.2,1)",
                }}
              />
              <div
                style={{
                  fontFamily: T.fontMono,
                  fontSize: 8.5,
                  color: b.fresh ? T.volt : T.fg3,
                  letterSpacing: 0.3,
                }}
              >
                {b.label}
              </div>
            </div>
          ))}
        </div>
      </div>

      <div
        style={{
          marginTop: 16,
          display: "flex",
          flexWrap: "wrap",
          gap: 6,
        }}
      >
        <Pill variant="for_sale">ABSORPTION · STRONG</Pill>
        <Pill variant="for_trade">TEMPO · ACCELERATING</Pill>
      </div>

      <div
        style={{
          marginTop: 18,
          paddingTop: 14,
          borderTop: `1px solid ${T.frostDiv}`,
          display: "flex",
          justifyContent: "space-between",
          flexWrap: "wrap",
          gap: 6,
          fontFamily: T.fontMono,
          fontSize: 10,
          color: T.fg3,
          letterSpacing: 0.4,
        }}
      >
        <span>eBay Browse · 47 sales</span>
        <span>+ PSA · Heritage · Goldin</span>
      </div>
    </div>
  )
}

function AutoShowcaseCard() {
  return (
    <FrostCard hover={false} style={{ padding: 30 }}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}
      >
        <Kicker style={{ color: T.volt }}>AUTO-SHOWCASE · RULE</Kicker>
        <Pill variant="volt">
          <span
            style={{
              display: "inline-block",
              width: 5,
              height: 5,
              borderRadius: 3,
              background: T.volt,
              boxShadow: `0 0 5px ${T.volt}`,
              marginRight: 4,
              animation: "pulseGlow 1.4s ease-in-out infinite",
            }}
          />
          ACTIVE
        </Pill>
      </div>

      <div
        style={{
          marginTop: 22,
          fontFamily: T.fontDisplay,
          fontSize: 28,
          letterSpacing: -0.4,
        }}
      >
        Gem Mint Grails
      </div>
      <div
        style={{
          fontFamily: T.fontCaslon,
          fontStyle: "italic",
          fontSize: 13,
          color: T.fg2,
          marginTop: 4,
        }}
      >
        auto-curated · 14 pieces · last match 3d ago
      </div>

      <div
        style={{
          marginTop: 28,
          padding: 20,
          borderRadius: 12,
          background: "rgba(0,0,0,0.45)",
          border: `1px solid ${T.frostDiv}`,
          fontFamily: T.fontMono,
          fontSize: 12.5,
          color: T.fg1,
          lineHeight: 2.1,
        }}
      >
        <div>
          <span style={{ color: T.fg3 }}>WHEN</span>{" "}
          <RuleChip>grading_company</RuleChip>{" "}
          <span style={{ color: T.fg3 }}>=</span>{" "}
          <RuleChip tone={T.volt}>PSA</RuleChip>
        </div>
        <div>
          <span style={{ color: T.fg3 }}>AND</span>{" "}
          <RuleChip>grade</RuleChip>{" "}
          <span style={{ color: T.fg3 }}>≥</span>{" "}
          <RuleChip tone={T.volt}>9</RuleChip>
        </div>
        <div>
          <span style={{ color: T.fg3 }}>AND</span>{" "}
          <RuleChip>value</RuleChip>{" "}
          <span style={{ color: T.fg3 }}>≥</span>{" "}
          <RuleChip tone={T.volt}>$5,000</RuleChip>
        </div>
        <div style={{ marginTop: 10, color: T.fg3, fontSize: 11.5 }}>
          →&nbsp;&nbsp;auto-add to Showcase
        </div>
      </div>

      <div
        style={{
          marginTop: 22,
          paddingTop: 22,
          borderTop: `1px solid ${T.frostDiv}`,
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: 12,
        }}
      >
        {(
          [
            ["14", "MATCHED"],
            ["+3", "THIS MONTH"],
            ["LIVE", "STATUS"],
          ] as const
        ).map(([v, l], i) => (
          <div key={l}>
            <div
              style={{
                fontFamily: T.fontDisplay,
                fontSize: 30,
                letterSpacing: -0.5,
                color: i === 2 ? T.volt : T.fg1,
              }}
            >
              {v}
            </div>
            <Kicker style={{ fontSize: 9, marginTop: 4 }}>{l}</Kicker>
          </div>
        ))}
      </div>
    </FrostCard>
  )
}

function RuleChip({
  children,
  tone,
}: {
  children: React.ReactNode
  tone?: string
}) {
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        padding: "3px 10px",
        borderRadius: 6,
        background: tone ? `${tone}22` : "rgba(214,235,253,0.08)",
        border: `1px solid ${tone ? `${tone}66` : T.frostDiv}`,
        color: tone || T.fg1,
        fontFamily: T.fontMono,
        fontSize: 12,
        letterSpacing: 0.3,
        margin: "0 1px",
      }}
    >
      {children}
    </span>
  )
}
